leysö: clear compile run

compile:
	javac *.java

run:
	java Main

clear:
	clear

clean: rmUsr rmLib
	rm -f *.class
	clear

libSys:
	javac LibrarySystem.java

usrInt:
	javac User.java

usrAbs:
	javac AbstractUser.java

libStf:
	javac LibraryStaff.java

libUsr:
	javac LibraryUser.java

rmUsr:
	rm -f usr.csv

rmLib:
	rm -f lib.csv
